### ISSUE TITLE
Remove extraneous rendered {.underline} coming from both .rst and .md  

### ISSUE THREAD

**Issue by jpnavarro** [access-ci-org/Integration_Roadmaps#6]

**Comment by c-mart** [comment]
I dug into this. Pandoc's [default Markdown writer format](https://pandoc.org/MANUAL.html#pandocs-markdown) uses a [bracketed spans](https://pandoc.org/MANUAL.html#extension-bracketed_spans) extension where syntax like this is meaningful:

```
[This text is underlined]{.underline}
```

This syntax isn't part of [CommonMark](https://commonmark.org), and MyST doesn't parse it, so it gets rendered as literal content on the site.

I tried re-running Pandoc to convert a `.docx` file, specifying `--to commonmark` instead of `--to markdown`. Along with some other minor changes, this changed the output from

```
Resource providers needing assistance with roadmap activities may submit a ticket using the [[Support Portal ticket form]{.underline}](https://support.access-ci.org/open-a-ticket).
```

...to...

```
Resource providers needing assistance with roadmap activities may submit a ticket using the [<span class="underline">Support Portal ticket form</span>](https://support.access-ci.org/open-a-ticket).
```

That HTML span is mostly harmless: there is no CSS `underline` class in the rendered site, so it doesn't affect presentation. That said, it's still cruft in the source that we're better off without.

I get even better results with Pandoc with `--to commonmark-raw_html` (disabling the [raw_html](https://pandoc.org/MANUAL.html#extension-raw_html) extension). A perfect Markdown link.

```
Resource providers needing assistance with roadmap activities may submit a ticket using the [Support Portal ticket form](https://support.access-ci.org/open-a-ticket).
```

Before/after comparison of rendered site:

![image](https://user-images.githubusercontent.com/13605043/224420801-0667faa7-a4f2-4b21-9119-0edef0fd963b.png)

So, I may suggest we re-run the import with `--to commonmark-raw_html` instead of `--to markdown`. First, let's answer these questions:
- Are there already hand-made changes to the Markdown files (done after import) which would be over-written by a re-import from the `.docx` source?
- Does change have other effects, good or bad?

**Comment by jpnavarro** [comment]
No changes to Markdown yet. At this point we should be safe making automated conversion improvements like you suggest. I'll try this and we can deal with other effect, or back off if necessary. Thanks!

**Comment by jpnavarro** [comment]
I tried it, closing for now. We can re-open if we're not happy later.
